version: '3.9'
services:
  # MariaDB Database to use with local development
  db:
    image: mariadb
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=top-secret
      - MARIADB_ROOT_PASSWORD=super-top-secret
    ports:
      - 3306:3306
  db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
