# Postgres Docker
version: '1.0'
services:
  postgres:
    image: postgres:13
    ports:
      - '5450:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'prisma-rds'
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_is_ready:
    image: postgres
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  db_data:
